enc:
  required: True
  type: dict
  schema:
    utm_zone:
      required: True
      type: integer
    size:
      required: True
      type: list
      maxlength: 2
      schema:
        type: float
        min: 1.0
    origin:
      required: True
      type: list
      maxlength: 2
      schema:
        type: float
    center:
      required: False
      type: list
      maxlength: 2
      schema:
        type: float
    buffer:
      required: True
      type: integer
      min: 0
    tolerance:
      required: True
      type: float
      min: 0
    layers:
      required: True
      type: list
      allowed: ["seabed", "land", "shore"]
      minlength: 1
      maxlength: 3
    depths:
      required: True
      type: list
      minlength: 1
      schema:
        type: integer
        min: 0
    files:
      required: True
      type: list
      minlength: 1
      schema:
        type: string
    new_data:
      required: True
      type: boolean
    raw_data:
      required: True
      type: boolean
    border:
      required: True
      type: boolean
    verbose:
      required: True
      type: boolean
    center_lla:
      required: False
      type: list
      maxlength: 2
      schema:
        type: float
    sim_callback_time:
      required: True
      type: float
    local_traffic_publish_timer:
      required: True
      type: float
      
display:
  required: True
  type: dict
  schema:
    dpi:
      required: True
      type: integer
    anchor:
      required: True
      type: string
    resolution:
      required: True
      type: integer
    fullscreen_mode:
      required: True
      type: boolean
    colorbar_mode:
      required: True
      type: boolean
    dark_mode:
      required: True
      type: boolean
    draw_names:
      required: True
      type: boolean
    nr_of_shadow_ships:
      required: True
      type: integer

ais:
  required: true
  type: dict
  schema:
    timer_period:
      required: True
      type: float